### ISSUE TITLE
why it does not work when i use   fid_ps2kb_write

### ISSUE THREAD

**Issue by vipmengfeng** [ndusart/ps2-keyboard#1]
this is my code bellow:

```
#include FidPS2Keyboard.h 
void setup() {
fid_ps2kb_init(5,3);
Serial.begin(9600);
}

void loop() {
 delay(100);;
 fid_ps2kb_write(0x1c);
 fid_ps2kb_write(0xf0);
 fid_ps2kb_write(0x1c);
  delay(2000);
}
```

when i run this code,my pc has nothing print,i don't know why,

**Comment by ndusart** [comment]
It seems that there was a typo in the readme file of the project.

FidPS2Keyboard (fid_ps2kb_\* functions) are for communicating to a keyboard.
In order to send keystrokes to a computer, you have to use fid_ps2h_\* functions and include FidPS2Host.h.

Sorry for the error in the documentation. It is fixed now.
Please tell me if it solves your problem.

**Comment by vipmengfeng** [comment]
I‘m sorry,It still doesn't work now...

I want to use arduino Emulating ps-2 keyboard.
for  example:I want to  send  "A" to the computer,then the computer can print "A" in a txt document.
how do i use your code in arduino
I try to use fid_ps2h_write(0x1c);
but it did nothing 

I read the source code,and i can't understand  how  the FidPS2Keyboard.h work,it does not use for Emulating keyboard?

**Comment by vipmengfeng** [comment]
I tried the code on arduino uno and arduino yun , all of them  doesn't work,
Look forward to your reply.thanks very much!

**Comment by ndusart** [comment]
> I read the source code,and i can't understand how the FidPS2Keyboard.h work,it does not use for Emulating keyboard?

Names can be confusing but FidPS2Keyboard is representing a PS/2 keyboard connected to the arduino, hence the arduino playing the role of the host.
The FidPS2Host represent a host connected to the arduino, and the arduino is then emulating a PS/2 keyboard.

> I try to use fid_ps2h_write(0x1c);
> but it did nothing 

Yes, it is the correct use and correct code for the "pressing the A key" event.

It is quite a long time since I have posted this code and played with a PS/2 keyboard, so I am a bit rusty to find out your problem. But it seems some values are hardcoded in the source code for the used pins, to gain some times avoiding shift operations.
These are the constants defined in the headers (e.g. HOST_CLOCK_SET_MASK).

You could change these values to match the correct values for the pins you are using, or simply delete the #define statements to reenable dynamic mask creation.
But the simplest is to use the PIN 2 for the CLOCK and the PIN 4 for DATA.

``` cpp
#include FidPS2Host.h 
void setup() {
fid_ps2h_init(4,2);
Serial.begin(9600);
}

void loop() {
 delay(100);
 fid_ps2h_write(0x1c);
 fid_ps2h_write(0xf0);
 fid_ps2h_write(0x1c);
  delay(2000);
}
```

I do not have a computer with a PS/2 port right now to test it unfortunately.
But the implementation works, there is an arduino running for 2 years now using this code for a cash register system, intercepting keystrokes from a keyboard and forwarding them to the computer and allowing to insert other keys through the serial bus. ;)

I certainly should improve the README file and modify the code to get rid of these hardcoded values...

Please note that this code is very low-level and does not reply to commands of the host, it is up to you to do that. Not really sure if it is mandatory for your computer, I remember I had to respond to a RESET (0xFF) command to be able to send keys afterwards.

It could be a good idea to just print the bytes you receive from it, and then implement a simple code that aknowledge the commands and respond to them. You will at least have a confirmation that the communication is possible when you will see that you receive commands.

Or better, if you have a working PS/2 keyboard, connect it through your arduino using pins 3 and 5, so that you can just write to the host what you receive from the keyboard and the reverse, and print it all to the serial bus. Then you could figure out easily what your computer is expecting from you.

Here is an example code for printing what the computer send. Uncomment the lines if you have a keyboard as well.

``` cpp
#include <FidPS2Keyboard.h>
#include <FidPS2Host.h>

void setup() {
  Serial.begin(115200);
  //fid_ps2kb_init(5, 3);
  fid_ps2h_init(4,2);
}

uint8_t value = 0;

void loop() {
  /*while( fid_ps2kb_read(&value) )
  {
    Serial.print("< ");
    Serial.println(value, HEX);
    fid_ps2h_write(value);
  }*/
  while( fid_ps2h_read(&value) )
  {
    Serial.print("> ");
    Serial.println(value, HEX);
    //fid_ps2kb_write(value);
  }
}

```

Note: for this library, prefer to use higher baud rates (prefer 115200 to 9600) for your serial bus as the PS/2 protocol as some timing requirements that could be hard to match if the serial bus take too much time sending bytes.

**Comment by vipmengfeng** [comment]
thanks for your reply，this is my code bellow:
`#include FidPS2Keyboard.h
#include FidPS2Host.h

void setup() {
  Serial.begin(115200);
  fid_ps2h_init(4,2);
}

uint8_t value = 0;

void loop() {
   while( fid_ps2h_read(&value) )
  {
    Serial.print("> ");
    Serial.println(value, HEX);
    //fid_ps2kb_write(value);
  }
}
`
 I can receive from computer,and print "FF" to the serial bus ,but how can I respond to a RESET (0xFF) command ?
I use 
`if(value==0xff)
  {
    fid_ps2h_write(0xFA);
}`
then I send 0x1c to computer ,but it seems didn't work, nothing print at all

**Comment by ndusart** [comment]
At least you got a byte from the host :)

Let's try with that code for testing:

``` cpp
#include <FidPS2Host.h>

void setup() {
  Serial.begin(115200);
  fid_ps2h_init(4,2);
  delay(100);
  fid_ps2h_write(0xAA);
}

uint8_t value = 0;

int fromHex(char ch) {
  if(ch >= '0' && ch <= '9')
    return ch - '0';
  else if(ch >= 'A' && ch <= 'F')
    return ch - 'A' + 10;
  else if(ch >= 'a' && ch <= 'f')
    return ch - 'a' + 10;

  return 0;
}

void loop() {
  while( fid_ps2h_read(&value) )
  {
    Serial.print("> ");
    Serial.println(value, HEX);
  }
  if (Serial.available() > 1) { // user input over serial line
    int incomingByte = (fromHex(Serial.read()) << 4) + fromHex(Serial.read());
    Serial.print("< ");
    Serial.println(incomingByte, HEX);
    fid_ps2h_write(incomingByte);
  }
}
```

You can then play using the serial console and try some sequence of commands. Type in the console the bytes to send to the computer in hexadecimal without "0x".

Normally, after a 0xFF command, you should ack with a 0xFA and follow it with a 0xAA telling the reset is over.

Some computers could send a sequence of
- 0xFF to reset to keyboard -> respond with 0xFA 0xAA (wait for about 500ms between the two)
- 0xF5 to disable scan codes -> respond with 0xFA and do not send key codes afterwards
- 0xF2 to get the device ID -> respond with 0xFA (and follow with 0xAB 0x83 but some keyboards do not)
- 0xF4 to reenable the keyboard -> respond with 0xFA and you can now send keystrokes

It is also a good practice to send 0xAA just after powering up.

All commands sent from the host needs to get a correct response or the host will not listen and just try to reset your device.

You should not implement all the commands to have a working solution.
Normally, you have at least to ACK (0xFA) all of them. I can only think about two commands that do not expect an ACK: 
- 0xEE  (echo) -> you should respond with 0xEE
- 0xFE (resend) -> resend the last byte

**Comment by vipmengfeng** [comment]
when I upload the code to Arduino, I must take out the ps-2 Interface from computer,and touch it again,
sometimes the serial bus can print 'FF' ,sometimes not.

I tried it in your way,and  the serial bus  always print '0'

when I restart the computer ,the serial bus print a lot

**Comment by vipmengfeng** [comment]
i found that ,different Arduino board ,the Interrupt pin is different too, i used the Arduino yun which  likes the Arduino Leonardo ,it's Interrupt pin is 0 for 3 pin Numbers, the 1 interrupt pin is for the 2 pin numbers, can you understand me ? And i modify your source code ,am i right?

**Comment by vipmengfeng** [comment]
Can you give me your e-mail address? so i can send some screenshots to you.

**Comment by ndusart** [comment]
Ha yes, I used the Arduino Uno and the interrupt numbers are inverted with regard to the Arduino Leonardo. I should have used the function `digitalPinToInterrupt` to have the corresponding interrupt number.

You have to modify the value of `mIrqNum` in `fid_ps2h_init`

**Comment by vipmengfeng** [comment]
Thank you very much! This problem has been bothering me for a lot of days.I can't solve it.Looking forward to you can help me to solve it

**Comment by vipmengfeng** [comment]
i send a screenshot to your email.

No matter what type in by using the serial console,it returns '0'

if  nothing to type in ,it will be print "FC or FE" non-stop

**Comment by Harvie** [comment]
> You have to modify the value of mIrqNum in fid_ps2h_init

I guess the library should autodetect this!
